basePath: /
definitions:
  handlers.Greetings:
    properties:
      message:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: gonzalezlrjesus@gmail.com
    name: Jesus Gonzalez
    url: https://github.com/gonzalezlrjesus
  description: This is a sample to understand how swag works
  title: Jesus Gonzalez's Swagger Example API
  version: "0.1"
paths:
  /:
    post:
      consumes:
      - application/json
      description: Show message
      parameters:
      - description: Show Body message
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/handlers.Greetings'
      - description: Basic token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Show message
      tags:
      - Show message
swagger: "2.0"
